### ISSUE TITLE
Feature request: specify other services ("Anliegen")

### ISSUE THREAD

**Issue by cpockrandt** [sonac/burgerbot#1]
Hi @sonac,

thanks for your bot, it's super helpful! I noticed that not all appointments can be used for all services ("Anliegen"). Your current script shows appointments for "Wohnungsanmeldungen" but if you need other services (e.g., "Beglaubigungen" with id 121701), the slots that the bot reports, are usually not eligible for those other services.

Would it be possible for you to extend the script that you pass an optional ID for anliegen to the [URL](https://github.com/sonac/burgerbot/blob/83803c2dac79fd956e6017af33ac50a8208f41f5/burgerbot.py#L18) when starting the job?

**Comment by sonac** [comment]
hey there, alright, that sounds reasonable. I'll need to think a bit about how to structure it since the current setup is not covering different interactions with different users.

**Comment by Mic4luv07** [comment]
Hello. I'm also frustrated in the way I kept looking for dates for registration. Please is there a way u can be of assistance to me?

**Comment by sonac** [comment]
finally got my hands onto it: https://github.com/sonac/burgerbot/pull/2

**Comment by cpockrandt** [comment]
Thank you!!! I'll try it out right away! :)
