### ISSUE TITLE
Is the tool down?

### ISSUE THREAD

**Issue by nicbou** [sonac/burgerbot#11]
Two people have written to me because the bot has no new appointments since a few days. They think it's affiliated with All About Berlin. Is the Telegram still working fine?

**Comment by IlyaMelikAdamov** [comment]
Hey, the app has been silent so I've decided to check the Bürgeramt site in parallel - and it seems to show appointments while the Telegram app is silent.

**Comment by sonac** [comment]
thanks for raising this, there were some network issues for a while in the droplet and it seems that one of the threads died in a meantime. I've restarted it for now, but need to work on some sort of automatic way to detect such issues 🤔

**Comment by nicbou** [comment]
You could register to the websockets server linked above. It will be maintained for as long as the city allows it to exist.

Otherwise, aren't tickets from well-meaning people sort of automatic? :P
