### ISSUE TITLE
Bot not running

### ISSUE THREAD

**Issue by candyman2903** [sonac/burgerbot#13]
Hello, the bot does not want to run with me.

Installed the Telegram module via pip:
`pip install python-telegram-bot --upgrade`

When starting I get the following message:

```
python burgerbot.py
Traceback (most recent call last):
   File "/home/username/burgerbot/burgerbot.py", line 233, in <module>
     Main()
   File "/home/username/burgerbot/burgerbot.py", line 224, in main
     bot = bot()
   File "/home/username/burgerbot/burgerbot.py", line 57, in __init__
     self.updater = Updater(os.environ["MY TELEGRAM API KEY"])
   File "/usr/lib/python3.10/os.py", line 679, in __geitem__
     raise KeyError(key) from None
KeyError: 'MY TELEGRAM API KEY'

```
Is anyone able to help me?

Furthermore, I noticed that the service IDs for:
```
120680: 'Beglaubigungen',
120701: 'Personalausweis beantragen',
```

have changed to:
```
121701: 'Beglaubigungen',
120703: 'Personalausweis beantragen',
```

Greetings Mike

**Comment by sonac** [comment]
if you want to run your own instance of the bot - you need to register one (read more here: https://core.telegram.org/bots) and then provide the API key that you would get from Botfather as an env var

Regarding the service IDs - thanks, I will adapt!
