### ISSUE TITLE
Seems to not work for service 318998

### ISSUE THREAD

**Issue by x-ji** [sonac/burgerbot#21]
Service 318998 'Einbürgerung - Verleihung der deutschen Staatsangehörigkeit beantragen' seems to be special in that it's tied to a particular district. When I try the URL from the source code (Note that I put "318998" after the `anliegen[]=` part)

`https://service.berlin.de/terminvereinbarung/termin/tag.php?termin=0&anliegen[]=318998&dienstleisterlist=122210,122217,327316,122219,327312,122227,327314,122231,327346,122243,327348,122252,329742,122260,329745,122262,329748,122254,329751,122271,327278,122273,327274,122277,327276,330436,122280,327294,122282,327290,122284,327292,327539,122291,327270,122285,327266,122286,327264,122296,327268,150230,329760,122301,327282,122297,327286,122294,327284,122312,329763,122314,329775,122304,327330,122311,327334,122309,327332,122281,327352,122279,329772,122276,327324,122274,327326,122267,329766,122246,327318,122251,327320,122257,327322,122208,327298,122226,327300,121362,121364&herkunft=http%3A%2F%2Fservice.berlin.de%2Fdienstleistung%2F120686%2F`

I get an error page, which doesn't happen with the other services.

Could you confirm that the bot is working for 318998? My district is one that provides online appointment (at this link https://service.berlin.de/terminvereinbarung/termin/tag.php?termin=1&dienstleister=324261&anliegen[]=318998&herkunft=1) so the bot would be really helpful to me.

I guess a solution would be to list separate services for 318998 Einbürgerung based on the district, instead of putting them under the same service. Does this make sense? The user is likely to only want to subscribe to appointments from their own district anyways given the nature of this service. (From [this page](https://service.berlin.de/dienstleistung/318998/) there are currently 3 districts that offer online booking of appointments for this service.)

**Comment by sonac** [comment]
hm, seems you're right, I will try to fix this over the weekend

**Comment by sonac** [comment]
this should be fixed now, if issue persists - please reopen
