### ISSUE TITLE
Improve the help message

### ISSUE THREAD

**Issue by damaru2** [sonac/burgerbot#3]
I could only figure out how to use the bot because I found this code and read it. Tell the user which are the services and id_services they can use with the bot

**Comment by bjajoh** [comment]
Very good idea! Until then, can you quickly tell me how to use it?
Thanks!!

**Comment by sonac** [comment]
the services names to their ids can be derived from the burgeramt appointment website, but you're right, its a bit confusing, I'm gonna try to add more meaningful description to it 👍

**Comment by antonkstk** [comment]
Hey! Not a python expert but it seems like when the new service is added, it is not reflected on the the /services response as it always returns same information. So I don't really know if the service I added was actually added or removed 🤔

**Comment by sonac** [comment]
> Hey! Not a python expert but it seems like when the new service is added, it is not reflected on the the /services response as it always returns same information. So I don't really know if the service I added was actually added or removed 🤔

`services` command shows available services overall, not those activated for the user, since normally I'd imagine any user would want only one service being active for them

**Comment by antonkstk** [comment]
> >`services` command shows available services overall, not those activated for the user, since normally I'd imagine any user would want only one service being active for them
>
Would be super cool to have an option to see the service ID of the currently active search. My use case is that I want to get an appointment to exchange the driving licence, I found the ID of that service in the url and I added it via the /add_service 327537.

**Comment by antonkstk** [comment]
> service `327537 - Fahrerlaubnis - Umschreibung einer ausländischen` added

Thanks a lot! 🤝
