### ISSUE TITLE
New service (registration of foreign child born in Berlin)

### ISSUE THREAD

**Issue by milosmns** [sonac/burgerbot#43]
https://service.berlin.de/dienstleistung/324269/en/

I assume the ID is `324269`.

Do we just add it to the array in the parser? If yes, I can make a PR.

**Comment by sonac** [comment]
I think this one was added here: https://github.com/sonac/burgerbot/pull/42

**Comment by milosmns** [comment]
Yes that's it. But I don't get it from the bot 😕 shouldn't it be also in the parser and not only there?

**Comment by sonac** [comment]
> 

bot sends the service ids to the parser and it injects them into the URL https://github.com/sonac/burgerbot/blob/master/parser.py#L78

you need to enable it in telegram itself, but unfortunately, it's still not a guarantee that you will get a notification immediately, in most cases except for Anmeldung the appointments are pretty rare smh
